name: rltut
description: My second attempt to follow the Roguelike Tutorial using Dart and the malison package.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  malison: any
  piecemeal: any

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
